---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ printf "%s-%s" .Release.Name (default .Chart.Name .Values.nameOverride) | trunc 63 | trimSuffix "-" }}-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: webapp
    spec:
      containers:
        - name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}-app
          image: ghcr.io/sebi364/webapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.db.host | default "quotes-db" }}
            - name: DB_DATABASE
              value: {{ .Values.db.database | default "quotes" }}
            - name: DB_USER
              value: {{ .Values.db.user | default "backend" }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password | default "changeme" }}
