apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: ghcr.io/sebi364/webapp:latest
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: shared-configs
                key: MYSQL_HOST

          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: shared-configs
                key: MYSQL_DATABASE

          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: shared-configs
                key: MYSQL_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api-server